server:
  port: 8000
  servlet:
    context-path: /spam
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://192.168.0.64:3306/spam?serverTimezone=Asia/Seoul
    username: icia97
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources: 
      static-locations: classpath:/static/
     
  mail:
    host: smtp.gmail.com
    port: 465
    username: byyb2696@gmail.com
    password: btsqzqxlkcujzxdo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

mybatis:
  type-aliases-package: com.spam9700.spam.dto
  mapper-locations: classpath:/mappers/*.xml
  # configuration:
    # map-underscore-to-camel-case: true
  

  
  
  
    
