server:
  port: 8000
  servlet:
    context-path: /spam
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spam?serverTimezone=Asia/Seoul
    username: icia97
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp