server:
  port: 8000
  servlet:
    context-path: /spam
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://106.243.194.229:3100/spam?serverTimezone=Asia/Seoul
    username: icia97
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources: 
      static-locations: classpath:/static/
     
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
